### ISSUE TITLE
Minecraft 1.7.2

### ISSUE THREAD

**Issue by Xephi** [timvisee/dungeon-maze#23]
I'll make this issue as a todo list :
- Fix generator problem, need to rework it due to some change with new biomes + crash on world create
- Implement custom rooms generation
- Implement custom rooms schematics
- Add support to Forge ( mcpc+ )
- Add a full config for items in chests
- Add some new awesome stuff :D

**Comment by sgdc3** [comment]
Obsolete issue

**Comment by timvisee** [comment]
The main point of the issue is obsolete yeah, although it would be great if the other points made, not related to Minecraft 1.7.2 could be added. 
Maybe the addition of Spigot support would be a great.

**Comment by sgdc3** [comment]
Just rename it :)

**Comment by Xephi** [comment]
So outdated issue :D
