### ISSUE TITLE
Spawners generate as/become pig spawns. #1.12.1

### ISSUE THREAD

**Issue by AidanNye** [timvisee/dungeon-maze#60]
Spawners generate as/become pig spawns.
_-Spigot 1.12.1
-No other plugins._
I assume something changed in the way spigot/minecraft handles spawners or NBT tags but im no programmer so idk.

**Comment by timvisee** [comment]
Hello,

First of all, thank you for the report.

As you might have noticed, I don't actively maintain my Minecraft/Bukkit plugins anymore.
I do have some free time however this week. I'm happy to take a look at it and I'm sure it won't be too hard to fix.

So, I'll try to release a fix for you as soon as possible.

Just one other thing, what version of Dungeon Maze are you using?

Tim Visée

**Comment by timvisee** [comment]
Hello,

I've identified the problem, and was able to fix it.

There's one problem however. In the current version I'm working on items won't spawn properly in chests, all chests are empty.

I'll have to fix that issue first, because I'm able to release an update for you with the issue fixed. Sorry for that.

I'll keep you updated.

Tim Visee

**Comment by timvisee** [comment]
Before I officially release the update that has a fix for this issue, you may use a snapshot of the current build.

There are quite a few things that have changed (mostly internally) and I haven't documented these changes yet.

The snapshot should work fine however if you replace the Jar file of the plugin you're currently running. You probably won't even notice anything has changed. It does have some debug properties enabled however.

You can download the current snapshot from here:
http://ci.xephi.fr/job/DungeonMaze/618/artifact/target/

Automatic updating is disabled in this snapshot. So please update the plugin manually as soon as a proper version has been released.

Tim Visée

**Comment by AidanNye** [comment]
Thanks for the updates on your progress. Apologies for the lack of
responses but i was actually away camping.

I will test the snapshot tomorrow and see how it goes in regards to the
chests you may be able to fill the chests post chunk generation by
replacing the empty chests with "Full" chests although that may be outside
the scope of your plugin never the less thanks for any and all the work you
have put into the plugin.
~Regards Aidan
