### ISSUE TITLE
update to 1.13.1

### ISSUE THREAD

**Issue by thunderlight411** [timvisee/dungeon-maze#70]
Are there any plans for updating to 1.13.1 ?
I like the concept so a upgrade of the plugin looks great

**Comment by sgdc3** [comment]
@timvisee if you need any help updating it just let me know ;)

**Comment by timvisee** [comment]
@thunderlight411 I do not plan to update it myself, because I sadly don't have the time for it. Have you tried running the plugin? Maybe it works. I'm unable to test it out at this time.

@sgdc3 That would be amazing, if it isn't too much work. Might just be a dependency update of course.

**Comment by thunderlight411** [comment]
@timvisee i have tried running it but got some error during world generation : https://pastebin.com/njyFcieg

@sgdc3 if you are willing to update it to 1.13.1 it would be great.

i have tried running it on 1.12.2 and it looks great

**Comment by sgdc3** [comment]
The issue is that 1.13 changed the world generator format, i'll have a quick look.

**Comment by sgdc3** [comment]
I forgot about the deprecation of block IDs ;_; the plugin needs a major rewrite in order to work.

**Comment by timvisee** [comment]
Damn, too bad. Thank you for looking into it however!

As I said I don't have the time right now to do such an update.

@thunderlight411 I'm afraid there won't be an update for 1.13.

**Comment by sgdc3** [comment]
I can try to do it slowly, but it will 100% break something, as the chunk generation/material system changed entirely.

**Comment by thunderlight411** [comment]
Thanks for looking into it,
If its not going to work or to much effort its oke,
then i will look into something simulare or check for a combination with viaversion to offer it in my network.

**Comment by sgdc3** [comment]
keep this open please

**Comment by thunderlight411** [comment]
Oké will open it again.
was thinking that it was not going to work for you guys to update to 1.13.1

**Comment by sgdc3** [comment]
not atm, maybe in the future
