### ISSUE TITLE
Update for 1.13 and 1.14 ?

### ISSUE THREAD

**Issue by HolographicWings** [timvisee/dungeon-maze#71]

**Comment by timvisee** [comment]
I do not intent to update this plugin for 1.13 and above. I'm very sorry.

**Comment by HolographicWings** [comment]
can i try to do it ?

**Comment by timvisee** [comment]
@HolographicWings Of course. The project is open source.

Feel free to fork it and give patching it a try.

Any changes to fix compatibility with new Minecraft versions are welcome through a pull request.

**Comment by timvisee** [comment]
I'll close this for now.

Feel free to reopen it if you have any further questions or updates.
